import { spawn, execSync } from "child_process";
import * as fs from "fs";
import * as path from "path";

/**
 * Starts the Agent 365 mock tooling server and configures Claude Code
 * to connect to it.
 *
 * The mock server simulates MCP server interactions without external
 * dependencies like authentication or network access.
 *
 * Usage: npm run mock
 */

const MOCK_ENDPOINT = "http://localhost:5309";
const ENV_PATH = path.resolve(__dirname, "..", ".env");

async function main(): Promise<void> {
  console.log("=== Agent 365 Mock Server ===\n");

  // Step 1: Ensure .env points to mock server
  const envContent = [
    "# Mock Server Configuration (auto-generated by start-mock)",
    `MCP_PLATFORM_ENDPOINT=${MOCK_ENDPOINT}`,
    "NODE_ENV=development",
  ].join("\n");

  fs.writeFileSync(ENV_PATH, envContent + "\n", "utf-8");
  console.log(`.env configured for mock server at ${MOCK_ENDPOINT}\n`);

  // Step 2: Try to start the A365 mock server
  console.log("Starting A365 mock tooling server...");
  console.log("(If this fails, install A365 CLI: npm install -g @microsoft/agent365-cli)\n");

  try {
    const mockProcess = spawn("a365", ["develop", "start-mock-tooling-server"], {
      stdio: "inherit",
      shell: true,
    });

    // Give the server a moment to start
    await new Promise((resolve) => setTimeout(resolve, 3000));

    console.log(`\nMock server should be running at ${MOCK_ENDPOINT}`);

    // Step 3: Build project if dist doesn't exist
    const distPath = path.resolve(__dirname, "..", "dist", "index.js");
    if (!fs.existsSync(distPath)) {
      console.log("Building project...");
      execSync("npm run build", {
        cwd: path.resolve(__dirname, ".."),
        stdio: "inherit",
      });
    }

    // Step 4: Register with Claude Code
    console.log("\nRegistering mock bridge with Claude Code...");
    try {
      execSync("claude mcp remove agent365", { stdio: "ignore" });
    } catch {
      // Not previously registered
    }

    const cmd = `claude mcp add --transport stdio --scope local agent365 -- node "${distPath}"`;
    execSync(cmd, { stdio: "inherit" });

    console.log("\n=== Mock server running ===");
    console.log("Open Claude Code in this project to use Agent 365 tools.");
    console.log("Press Ctrl+C to stop the mock server.\n");

    // Keep running until the mock server exits
    mockProcess.on("exit", (code) => {
      console.log(`Mock server exited with code ${code}`);
      process.exit(code ?? 0);
    });
  } catch (err) {
    console.error("Failed to start mock server:", err);
    console.error(
      "\nAlternative: Start the mock server manually in a separate terminal:"
    );
    console.error("  a365 develop start-mock-tooling-server");
    console.error("\nThen in this terminal:");
    console.error("  npm run build");
    console.error("  npm run register");
    process.exit(1);
  }
}

main().catch((err) => {
  console.error("Error:", err);
  process.exit(1);
});
